### PR TITLE
_[v]snprintf() from Open Watcom might not nul terminate:

### PR DESCRIPTION
**Pull request by sezero**
their behavior is like _[v]snprintf() from msvcrt.dll. therefore, add
proper wrappers around _[v]snprintf() and use the SDL_ prefixed names
for them.

### CODE REVIEW

**Comment by sezero** [comment]
PING ?

**Comment by sezero** [comment]
PING?

**Comment by sezero** [comment]
I guess there is no interest in this. If that changes, cherry-pick
from my https://github.com/sezero/LIB-SDL-2014/tree/sezero branch.

**Comment by martiniturbide** [comment]
Hi sezero. I'm not a developer I only created this public repos for the source code to be more accessible to the community. Let me know what you require. Regards

**Comment by sezero** [comment]
I don't require anything: I just shared my changes. If anyone is ever
interested in them, they can find them here.

**Pull request closed without merging**
